.PHONY: setup
setup:
	ln -fs $(PWD)/settings.osx.json ~/Library/Application\ Support/Code/User/settings.json
	ln -fs $(PWD)/keybindings.osx.json ~/Library/Application\ Support/Code/User/keybindings.json
linux-setup:
	ln -fs $(PWD)/settings.linux.json ~/.config/Code\ -\ OSS/User/settings.json
	ln -fs $(PWD)/keybindings.linux.json ~/.config/Code\ -\ OSS/User/keybindings.json
