# ZSH_HOME
export ZSH_HOME=${HOME}/.zsh
# /etc/profile を読み込まないように
setopt no_global_rcs

# Local
export LANG='en_US.UTF-8'
export LC_CTYPE="en_US.UTF-8"

# Homebrew
eval $(/opt/homebrew/bin/brew shellenv)

# fpath
export FPATH="${ZSH_HOME}/site-functions:$HOMEBREW_PREFIX/share/zsh/site-functions:$HOMEBREW_PREFIX/share/zsh/functions:${FPATH}"

# system path
export PATH="${HOMEBREW_PREFIX}/bin:${HOMEBREW_PREFIX}/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:${PATH}"

# User-specific paths
export PATH="${HOME}/local/bin:${HOME}/bin:${PATH}"

# SUDO_PATH
typeset -xT SUDO_PATH sudo_path
typeset -U sudo_path
sudo_path=(
  /usr/local/sbin(N-/)
  /usr/sbin(N-/)
  /sbin(N-/)
)

# MANPATH
typeset -U manpath
manpath=(
  ${HOME}/local/share/man(N-/)
  /usr/local/share/man(N-/)
  /usr/share/man(N-/)
)

export EDITOR="nvim"

if [ "$(uname 2> /dev/null)" = "Linux" ]; then
  export XDG_DATA_HOME=/usr/local/share
fi

# Go
export PATH="$GOPATH/bin:$PATH"

# Python
export PATH="${HOME}/Library/Python/3.8/bin:$PATH"

# Ruby
export PATH="${HOMEBREW_PREFIX}/opt/ruby/bin:$PATH"
export PATH="$(gem environment gemdir)/bin:$PATH"

